### ISSUE TITLE
PR preview returns 'Invalid URI'

### ISSUE THREAD

**Issue by deniak** [tobie/pr-preview#54]
@iherman has reported several failures indicating 'Invalid URI' for links that apparently work.
See https://github.com/w3c/epub-3-wg-charter/pull/5

I'm suspecting a race condition here but it would be helpful to check the logs to narrow the issue.

**Comment by tobie** [comment]
Is this still an issue?

**Comment by iherman** [comment]
Yes. See, for example: 

- https://github.com/w3c/epub-3-wg-charter/pull/6
- https://github.com/w3c/epub-3-wg-charter/pull/11

I have, since then, removed the preview switch from the repository, that is why the same error does not appear in more recent PR-s.

To narrow things down: the problem seems to appear when one uses preview on pure HTML (ie, not respec) files, which is the case of this charter draft.

**Comment by tobie** [comment]
Thanks for the update! This seems like an escaping problem.

**Comment by tobie** [comment]
I think #58 should solve your issue.

I'll deploy it. Please let me know how it works for you.

**Comment by iherman** [comment]
Thanks @tobie, it does work! I have just tested it through https://github.com/w3c/epub-3-wg-charter/pull/39
