### ISSUE TITLE
Preview wasn't generated after just a Bikeshed include was modified

### ISSUE THREAD

**Issue by jyasskin** [tobie/pr-preview#88]
https://github.com/WICG/scheduling-apis/pull/33 modified only a Bikeshed include file, and PR-Preview didn't run to generate a preview.

**Comment by tobie** [comment]
Yeah, I have the following log for this PR:

```
Apr 26 10:48:42 pr-preview app/web.1 WICG/scheduling-apis/33: opened
Apr 26 10:48:42 pr-preview app/web.1 {
Apr 26 10:48:42 pr-preview app/web.1   installation_id: 10900,
Apr 26 10:48:42 pr-preview app/web.1   id: 'WICG/scheduling-apis/33',
Apr 26 10:48:42 pr-preview app/web.1   forcedUpdate: false,
Apr 26 10:48:42 pr-preview app/web.1   needsUpdate: false,
Apr 26 10:48:42 pr-preview app/web.1   updated: false,
Apr 26 10:48:42 pr-preview app/web.1   config: {
Apr 26 10:48:42 pr-preview app/web.1     src_file: 'spec/index.bs',
Apr 26 10:48:42 pr-preview app/web.1     type: 'bikeshed',
Apr 26 10:48:42 pr-preview app/web.1     params: { 'md-warning': 'not ready' }
Apr 26 10:48:42 pr-preview app/web.1   },
Apr 26 10:48:42 pr-preview app/web.1   previous: undefined,
Apr 26 10:48:42 pr-preview app/web.1   body: '@jyasskin This look right?'
Apr 26 10:48:42 pr-preview app/web.1 }
```

`needsUpdate: false` clearly indicates  that the program determined this PR had no relevant impact on the spec.

**Comment by tobie** [comment]
Yeah, I have the following log for this PR:

```
Apr 26 10:48:42 pr-preview app/web.1 WICG/scheduling-apis/33: opened
Apr 26 10:48:42 pr-preview app/web.1 {
Apr 26 10:48:42 pr-preview app/web.1   installation_id: [INSTALLATION_ID],
Apr 26 10:48:42 pr-preview app/web.1   id: 'WICG/scheduling-apis/33',
Apr 26 10:48:42 pr-preview app/web.1   forcedUpdate: false,
Apr 26 10:48:42 pr-preview app/web.1   needsUpdate: false,
Apr 26 10:48:42 pr-preview app/web.1   updated: false,
Apr 26 10:48:42 pr-preview app/web.1   config: {
Apr 26 10:48:42 pr-preview app/web.1     src_file: 'spec/index.bs',
Apr 26 10:48:42 pr-preview app/web.1     type: 'bikeshed',
Apr 26 10:48:42 pr-preview app/web.1     params: { 'md-warning': 'not ready' }
Apr 26 10:48:42 pr-preview app/web.1   },
Apr 26 10:48:42 pr-preview app/web.1   previous: undefined,
Apr 26 10:48:42 pr-preview app/web.1   body: '@jyasskin This look right?'
Apr 26 10:48:42 pr-preview app/web.1 }
```

`needsUpdate: false` clearly indicates  that the program determined this PR had no relevant impact on the spec.

**Comment by shaseley** [comment]
I noticed this again in the same repo in https://github.com/WICG/scheduling-apis/pull/76. I think the problem is that that repo has a separate spec directory, which is where includes are relative too, but this isn't taken into account by `scanIncludes`.

For example:

 - spec/
   - index.bs
   - include1.md
   - include2.md

And .pr-preview has `  "src_file": "spec/index.bs"`. When `scanIncludes` scans "spec/index.md", it finds "include1.md" (which doesn't exist) and not "spec/include1.md".

I have patch in progress to change `scanIncludes` to compute the spec directory from the `src_file` and prepend that to the included files (which will be a no-op if the spec file is in the repo root). It looks to me like includes need to be relative to the main spec file for both bikeshed and respec, even with more levels of subdirectories (manually tested), so something like that should work for both.
